### ISSUE TITLE
User can toggle emoji for each word.

### ISSUE THREAD

**Issue by LeoMouyna** [LeoMouyna/emojified#23]
## Description

Emoji will be displayed in a dedicated pop-up after user click or hover a key word.

## Task
 - [ ] Wrap key words on a `button` tag
 - [ ] Display a pop up on click with emoji
 - [ ] Style button and pop up for better display
